#!/usr/bin/env bash
#Block incoming traffic
#install UFW and update package lists
sudo apt-get update -y && sudo apt-get install -y ufw

#set the default policy to deny all incoming traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

#Allow incoming traffic on the required TCP ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo "y" | sudo ufw enable
echo "UFW Status:"
sudo ufw status verbose
