#!/usr/bin/env bash
# Configures a server with Nginx and a custom server

#Start by installing Nginx
apt-get update -y
apt-get install -y nginx

#set a custom header in the default site
sed -i "/server_name _;/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

#restart nginx restart
service nginx restart
