#!/usr/bin/env bash
# script: 1-install_nginx_web_server

# start by updating package list and install nginx
apt-get update -y
apt-get install -y nginx

# Replcing the default nginx page with the required text
echo "Holberton School" > /var/www/html/index.html

# restart the NGINX using service
service nginx restart

# ensuring Nginx starts on boot
update-rc.d nginx defaults

sleep 2
