#!/usr/bin/env bash
# configures Nginx to redirect to another page

# first install nginx if not installed
apt-get update -y
apt-get install -y nginx

#update index page
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Adding a redirect rule to the Nginx configuration
NGINX_CONF="/etc/nginx/sites-available/default"
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
TEMP_CONF="/tmp/nginx_redirect_conf"

# delete the previously added /redirect_me bloacks
sudo sed -i '/location \/redirect_me {/,/}/d' $NGINX_CONF

#Create a multiline config block in a temporary file
cat <<- EOF > $TEMP_CONF
        location /redirect_me {
                return 301 $REDIRECT_URL;
        }
EOF

# Use sed to insert the contents of the temp file
sudo sed -i "/location \/ {/r $TEMP_CONF" $NGINX_CONF

# Remove the temporary file
rm $TEMP_CONF

# check Nginx configuration for syntax errors
/usr/sbin/nginx -t
# reload nginx to apply changes
/usr/sbin/nginx -s reload

# Start Nginx if it was not running
if ! pgrep -x "nginx" > /dev/null; then
	/usr/sbin/nginx
fi

sleep 2
