#!/usr/bin/env bash
# configures Nginx to redirect to another page

# first install nginx if not installed
apt-get update -y
apt-get install -y nginx

#update index page
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

# Adding a redirect rule to the Nginx configuration
NGINX_CONF="/etc/nginx/sites-available/default"

# add the redirect block inside the defaut sever configuration
if ! grep -q "redirect_me" "$NGINX_CONF"; then
    sed -i '/listen 80 default_server;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' "$NGINX_CONF" 	
fi

# Verify nginx config
nginx -t

# Restart nginx safely
service nginx restart

# Wait to ensure reload
sleep 2
