#!/usr/bin/env bash
# Custom 404 page for Nginx

# Configuration variables
NGINX_CONF="/etc/nginx/sites-available/default"
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
ERROR_PAGE_FILE="/var/www/html/404.html"
CUSTOM_404_STRING="Ceci n'est pas une page"

#Install and setup the root page
apt-get update -y
apt-get install -y nginx

# Create the custom index.html
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# add the custom 404 page
#create the custom 404 page
printf "%s\n\n\n" "$CUSTOM_404_STRING" | sudo tee "$ERROR_PAGE_FILE" > /dev/null

# Insert the error page directive into the Nginx config
ERROR_PAGE_DIRECTIVE="error_page 404 /404.html;"
sudo sed -i "/server_name _;/i$ERROR_PAGE_DIRECTIVE" $NGINX_CONF

# removing unnecessary files that could cause conflict
sudo sed -i '/location \/redirect_me {/,/}/d' $NGINX_CONF
sudo sed -i '/location = \/404.html {/,/}/d' $NGINX_CONF
# THE Redirection
TEMP_CONF="/tmp/nginx_redirect_conf"

# CREATE THE multiline config block
cat <<- EOF > $TEMP_CONF
	location /redirect_me {
		return 301 $REDIRECT_URL;
	}
	location = /404.html {
		internal;
	}
EOF

# Use sed to insert the contents of the temp file
sudo sed -i "/location \/ {/r $TEMP_CONF" $NGINX_CONF

# Remove the temporary file
rm $TEMP_CONF

# ensure the Nginx worker can always read the file
sudo chown www-data:www-data "$ERROR_PAGE_FILE"
sudo chmod 644 "$ERROR_PAGE_FILE"

# Check Nginx configuration for syntax errors
/usr/sbin/nginx -t

# Reload Nginx to apply changes
/usr/sbin/nginx -s reload

# Fallback: Start Nginx if it was not running
if ! pgrep -x "nginx" > /dev/null; then
    /usr/sbin/nginx
fi
sleep 2
