#!/usr/bin/env bash
# Custom 404 page for Nginx

NGINX_CONF="/etc/nginx/sites-available/default"
CUSTOM_404_PAGE="/var/www/html/404.html"
# 1.Update package lists and install
apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > "$CUSTOM_404_PAGE"

# Add the error_page configuration if not already there
if ! grep -q "error_page 404" "$NGINX_CONF"; then
	    sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www;\n\t\tinternal;\n\t}' "$NGINX_CONF"
fi

# Test and restart nginx
nginx -t
service nginx restart
